
title: Trade Audit
author: Steven Skelton
email: tradeauditapp@gmail.com
description: >
  Social media fintwit is full of financial professionals and macro analysts. Do your due diligence and audit
  trading records before you invest your time and money.
twitter_username: tradeaudit
github_username:  stevenrskelton # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
permalink: pretty
