
title: Trade Audit
author: Steven Skelton
email: tradeauditapp@gmail.com
#limit 150 chars for Google
description: Social media is full of financial professionals and macro analysts, do your due diligence before investing your time and money.
twitter_username: tradeaudit
github_username:  stevenrskelton # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
permalink: pretty
url: "https://tradeaudit.app"
plugins:
  - jekyll-sitemap

include:
  - _pages