
title: Trade Audit App
author: Steven Skelton
email: tradeauditapp@gmail.com
#limit 150 chars for Google
description: Social media is full of financial professionals and macro analysts, do your due diligence before investing your time and money.
twitter_username: tradeaudit
github_username:  stevenrskelton # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
permalink: pretty
url: "https://tradeaudit.app"
#logo: /assets/images/favicon.ico
#og_image: /assets/images/favicon.png
#repository: tradeaudit.app/stevenrskelton.github.io
#locale: en-US
#breadcrumbs: true

analytics:
  provider: google-gtag
  google:
    tracking_id: "G-BENCY8HPLG"

plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

include:
  - _pages

footer:
  links:
    - label: "Terms of Use"
#      icon: "fab fa-fw fa-github"
      url: "/terms-of-use"
    - label: "Privacy Policy"
      url: "/privacy-policy"
    - label: "Cookie Policy"
      url: "/cookie-policy"
    - label: "Account Deletion"
      url: "/account-deletion"

navigation:
  - label: "Tracking Influencers"
    links:
      - label: "Do Their Trades Make Money?"
        url: "/"
      - label: "Influencer Rankings"
        url: "/rankings"
  - label: "Import From Social Media"
    key: "integrations"
    links:
      - label: "YouTube"
        url: "/youtube"
        img: "/assets/integrations/youtube.svg"
      - label: "Twitter / X"
        url: "/x"
        img: "/assets/integrations/x.svg"
      - label: "Substack"
        url: "/substack"
        img: "/assets/integrations/substack.svg"
      - label: "Web Pages"
        url: "/webpages"
        img: "/assets/integrations/webpages.svg"
  - label: "Our Data Governance"
    links:
      - label: "Terms of Use"
        url: "/terms-of-use"
      - label: "Privacy Policy"
        url: "/privacy-policy"
      - label: "Cookie Policy"
        url: "/cookie-policy"
      - label: "Account Deletion"
        url: "/account-deletion"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      sitemap: true
      layout: "default"
      author_profile: false