
title: Trade Audit App
author: Steven Skelton
email: tradeauditapp@gmail.com
#limit 150 chars for Google
description: Social media is full of financial professionals and macro analysts, do your due diligence before investing your time and money.
twitter_username: tradeaudit
github_username:  stevenrskelton # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
permalink: pretty
url: "https://tradeaudit.app"
#logo: /assets/images/favicon.ico
#og_image: /assets/images/favicon.png
#repository: tradeaudit.app/stevenrskelton.github.io
#locale: en-US
#breadcrumbs: true

analytics:
  provider: google-gtag
  google:
    tracking_id: "G-BENCY8HPLG"

plugins:
  - jekyll-sitemap
  - jemoji
  - jekyll-include-cache

include:
  - _pages

footer:
  links:
    - label: "Terms of Use"
#      icon: "fab fa-fw fa-github"
      url: "/terms-of-use"
    - label: "Privacy Policy"
      url: "/privacy-policy"
    - label: "Cookie Policy"
      url: "/cookie-policy"
    - label: "Account Deletion"
      url: "/account-deletion"

navigation:
  - label: "Tracking Influencers"
    links:
      - label: "Which Trades Made Money?"
        url: "/"
      - label: "Influencer Rankings"
        url: "/rankings"
  - label: "Import From Social Media"
    key: "integrations"
    links:
      - label: <img src="/assets/integrations/yt_logo_rgb_light.png" alt="YouTube" class="navitem_logo">
        url: "/youtube"
      - label: <img src="/assets/integrations/substack_wordmark.png" alt="Substack" class="navitem_logo">
        url: "/substack"
      - label: <img src="/assets/integrations/x.svg" alt="Twitter" class="navitem_icon"><span style="color:#657786;vertical-align:middle;margin:0 10px;">/</span><img src="/assets/integrations/twitter-logo.svg" class="navitem_icon" alt="Twitter X logo" style="width:24px;position:relative;top:3px;max-height:24px;margin-top:-4px;">
        url: "/x"
      - label: <img src="/assets/integrations/webpages.svg" alt="Web" class="navitem_icon"><span class="navitem_text" style="color:#27ae60;padding-left:4px">Web Sites</span>
        url: "/webpages"
  - label: "Our Data Governance"
    links:
      - label: "Terms of Use"
        url: "/terms-of-use"
      - label: "Privacy Policy"
        url: "/privacy-policy"
      - label: "Cookie Policy"
        url: "/cookie-policy"
      - label: "Account Deletion"
        url: "/account-deletion"

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      sitemap: true
      layout: "default"
      author_profile: false